### ISSUE TITLE
Error  in course work 2

### ISSUE THREAD

**Issue by KaveeshTennakoon** [lithika-damnod/UoW#1]
An error occurs when a string is entered instead of an integer in the option menu.
Try using try-catch to handle the error.

**Comment by lithika-damnod** [comment]
Thank you for raising this issue ❤️
 I've acknowledged the problem regarding the error that occurs when a string is entered instead of an integer in the option menu. I've already implemented a fix for this issue in the latest merge request #2

Please feel free to review the changes in merge request #2. 
If you have any further suggestions or feedback, please let me know.

Best regards, 
Lithika Damnod
